name: publish
on: [pull_request_target]
permissions:
  contents: read
  packages: write
jobs:

  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: |
          docker build . --tag ghcr.io/yellowrook1/package:latest
          docker run ghcr.io/yellowrook1/package:latest
          docker push ghcr.io/yellowrook1/package:latest
