name: Create New Ref

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The name of the n<img>ew ref (e.g., refs/heads/new-branch)'
        required: true
      sha:
        description: 'The SHA of the <img>commit to point the new ref to'
        required: true

jobs:
  create-ref:
    runs-on: ubuntu-latest
    steps:
    - name: Create a new ref
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/git/refs \
        -d '{"ref": "${{ github.event.inputs.ref }}", "sha": "${{ github.event.inputs.sha }}"}'
